version: "3.7"
services:
  gnb-db:
    image: mysql:5.7
    restart: always
    container_name: gnb-db
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=asdfqwer1234
      - TZ=Asia/Seoul
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --lower_case_table_names=1
    volumes:
      - ./init/:/docker-entrypoint-initdb.d/
    networks:
      - default
      - our_net

  gnb-api:
    build:
      context: .
    ports:
      - "8080:8080"
    networks:
      - default
      - our_net

networks:
  our_net:
    driver: bridge